MVCInfosV2Web/Controllers/AdministrationController.cs
using Microsoft.AspNet.Identity;
using MvcInfos.Attributes;
using MvcInfos.Entities;
using MvcInfos.Entities.Firm;
using MvcInfos.Entities.Firm.Dictionary;
using MvcInfos.Entities.UserConfigurations;
using MvcInfos.Repository;
using MvcInfos.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using MvcInfos.Settings;
using MvcInfos.Extensions;
using MvcInfos.ActiveDirectory.Extensions;
using MvcInfos.ActiveDirectory;
using MvcInfos.IdentityConfig;

namespace MvcInfos.Controllers
{
	[AuthorizeActiveDirectory(Roles = "administrator_firm,administrator_server", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager")]
	public class AdministrationController : Controller
	{
		//private AdministrationViewModels avm = new AdministrationViewModels();
		private IApplicationRepository DBRepository { get; set; }
		private ApplicationUserManager UserManager { get; set; }
		private ApplicationRoleManager RoleManager { get; set; }

#if (DEBUG || RELEASE)
		private ActiveDirectorySetting ActiveDirectorySetting { get; set; }
		public AdministrationController(IApplicationRepository _repository, ApplicationUserManager _userManager, ApplicationRoleManager _roleManager, ActiveDirectorySetting _activeDirectorySetting)
		{
			ActiveDirectorySetting = _activeDirectorySetting;
#else
		public AdministrationController(IApplicationRepository repos, ApplicationUserManager _userManager, ApplicationRoleManager _roleManager)
        {

#endif
			RoleManager = _roleManager;
			UserManager = _userManager;
			DBRepository = _repository;

		}

		public ActionResult AdministrationFirm()
		{
			var applicationUser = DBRepository.Users.Find(User.Identity.GetUserId());
			AdministrationViewModels administrationViewModels = new AdministrationViewModels();
			//  adc.Firms.Find();
			foreach (var item in DBRepository.Users)
			{
				administrationViewModels.AllUsers.Add(new AdministrationEmployeePrintViewModels(item));
			}
			return View(administrationViewModels);

		}
		public ActionResult Index()
		{
			return RedirectToAction("Statistics");
		}

		public ActionResult Details(string id_user_to_details, EnumerableForDelete efd)
		{
			if (id_user_to_details == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			ApplicationUser au = DBRepository.Users.Find(id_user_to_details);

			if (au == null)
			{
				return HttpNotFound();
			}

			return PartialView(au);
			// return View(au);

		}


		public ActionResult EditDepartment(string id)
		{
			if (User.IsHasAccessRights(EnumerableRoles.user) || User.IsHasAccessRights(EnumerableRoles.manager))
			{
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
			}
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var employee = DBRepository.Users.Find(id);
			if (employee == null)
			{
				return HttpNotFound();
			}
			return View(new AdministrationEmployeePrintViewModels(employee));
		}

		[HttpPost]
		[ValidateJsonAntiForgeryToken]
		public async Task<ActionResult> EditDepartment([Bind] AdministrationModalEditDepartment data, int idFirm)
		{
			if (User.IsHasAccessRights(EnumerableRoles.user) || User.IsHasAccessRights(EnumerableRoles.manager))
			{
				return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
			}
			if (ModelState.IsValid)
			{
				if (User.IsHasAccessRights(EnumerableRoles.administrator_firm))
				{
					var currentUserId = User.Identity.GetUserId();
					var canUpdate = (await DBRepository.Firms.FindAsync(idFirm)).EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(currentUserId)).FirstOrDefault();
					if (canUpdate == null)
					{
						return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
					}
				}
				var department = (await DBRepository.Firms.FindAsync(idFirm)).Departments.Where(dep => dep.DepartmentID == data.idDepartment).FirstOrDefault();
				if (department == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
				}
				var userInDep = department.EmployeeFirms.Select(ef => ef.ApplicationUserId.Id).ToList();
				foreach (var user in userInDep)
				{
					if (data.Employees.Contains(user) == false)
					{
						var employeeForRemoveFromDep = (await DBRepository.Firms.FindAsync(idFirm)).EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(user)).FirstOrDefault();

						department.EmployeeFirms.Remove(employeeForRemoveFromDep);
					}
				}
				foreach (var item in data.Employees)
				{
					var employee = (await DBRepository.Firms.FindAsync(idFirm)).EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(item)).FirstOrDefault();
					department.EmployeeFirms.Add(employee);
				}
				department.Name = data.DepartmentName;
				DBRepository.Entry(department).State = EntityState.Modified;
				await DBRepository.SaveChangesAsync();
				return Json(new { code = HttpStatusCode.OK });
			}
			return Json(new { code = HttpStatusCode.InternalServerError });
		}

		public ActionResult Edit(string id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var employee = DBRepository.Users.Find(id);
			if (employee == null)
			{
				return HttpNotFound();
			}
			return View(new AdministrationEmployeePrintViewModels(employee));
		}

		// POST: Employees/Edit/5
		// Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
		// сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		[ActionName("Edit")]
		public ActionResult Edit([Bind(Include = "Id,Family_name,Name,Middle_name,BirthData,PhoneNumber,department_string,firm_string")] AdministrationUserModalWindow employee, string userID)
		{
			//if (ModelState.IsValid)
			//{
			//    var db_user = DBRepository.Users.Find(employee.Id);
			//    var firms_vved = employee.FirmString.Split(',');
			//    var users_in_firm = (
			//        from db_firm in DBRepository.Firms.ToList()
			//        from vved_firm in firms_vved
			//        where db_firm.Name.CompareTo(vved_firm) == 0
			//        select db_firm);
			//    foreach (var item in users_in_firm)
			//    {
			//        var item_ef = item.AddUser(db_user);
			//        db_user.Employee.AddToFirm(item_ef);
			//    }
			//    db_user.Employee.Person.MiddleName = employee.MiddleName;
			//    db_user.Employee.Person.Name = employee.Name;
			//    db_user.Employee.Person.FamilyName = employee.FamilyName;
			//    db_user.Employee.Person.BirthData = employee.BirthDate;
			//    db_user.Employee.EmployeeFirms.Last().EmploymentDate = DateTime.Now;
			//    db_user.PhoneNumber = employee.PhoneNumber;
			//    DBRepository.Entry(db_user).State = EntityState.Modified;
			//    await DBRepository.SaveChangesAsync();
			//    return RedirectToAction("AdminsServer");
			//}

			return PartialView("Admin/Modal/_modal_for_user", employee);
		}



		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> Delete(string id_user_to_delete = "", int idFirm = -1, int idDepartment = -1, EnumerableForDelete efd = EnumerableForDelete.None)
		{
			if (User.IsHasAccessRights(EnumerableRoles.administrator_server) || User.IsHasAccessRights(EnumerableRoles.administrator_firm))
			{
				switch (efd)
				{
					case EnumerableForDelete.Department:
						{
							if (idDepartment == -1)
							{
								return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Нет id отдела, удалить не возможно");
							}
							var Department_ = DBRepository.Departments.Find(idDepartment);
							if (Department_ == null)
							{
								return HttpNotFound();
							}
							DBRepository.Departments.Remove(Department_);
							await DBRepository.SaveChangesAsync();
							return RedirectToAction("Index");
						}


					case EnumerableForDelete.Firm:
						{
							if (idFirm == -1)
							{
								return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Нет id фирмы, удалить не возможно");
							}

							var Firm_ = DBRepository.Firms.Find(idFirm);
							if (Firm_ == null)
							{
								return HttpNotFound();
							}

							DBRepository.Firms.Remove(Firm_);
							await DBRepository.SaveChangesAsync();
							return RedirectToAction("Index");
						}
					case EnumerableForDelete.User:
						{
							if (id_user_to_delete.CompareTo("") == 0)
							{
								return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Нет id пользователя, удалить не возможно");
							}

							var Users_ = DBRepository.Users.Find(id_user_to_delete);
							if (Users_ == null)
							{
								return HttpNotFound();
							}
							var employee_ = DBRepository.Employees.Find(id_user_to_delete);
							if (employee_ == null)
							{
								//return HttpNotFound();
							}
							else
							{
								DBRepository.Employees.Remove(employee_);
							}
							DBRepository.Users.Remove(Users_);
							await DBRepository.SaveChangesAsync();
							return RedirectToAction("Index");
						}
					default:
						break;
				}
			}
			else
			{
			}
			return View();
		}

		[ActionName("_modal_for_user")]
		public async Task<ActionResult> ModalForUser([Bind(Prefix = "id_user_to_details")]string idUserToDetails, EnumerableForDelete efd)
		{
			if (idUserToDetails == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var user_ = DBRepository.Users.Find(idUserToDetails);
			if (user_ == null)
			{
				return HttpNotFound();
			}
			var Result = await Task.Run(async () =>
		   {
			   var empl1 = await DBRepository.Employees.Where(empl => empl.ApplicationUserId.Equals(idUserToDetails)).Select(_employee =>
			   new AdministrationUserModalWindow()
			   {
				   Email = _employee.ApplicationUser.Email,
				   UserName = _employee.ApplicationUser.UserName,

MVCInfosV2Web/Views/Settings/ActiveDirectory.cshtml
@{
	ViewBag.Title = "Active Directory";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.TitlePage = "Настройка сервера";
	ViewBag.TitlePageSmall = ViewBag.Title;
	ViewBag.UseSearch = false;
}

<div>
	@using (Html.BeginForm(null, null, FormMethod.Post, htmlAttributes: new { @id = "__AjaxAntiForgeryForm" } @*"EditDepartment", "Administration", new { idFirm = Model.idFirm, idDepartment = Model.idDepartment, efd = EnumerableForDelete.Department }*@))
	{
		@Html.AntiForgeryToken()
	}
</div>
@{
	var isUsing = ((bool)ViewData["IsUsingActiveDirectory"]) == true ? "checked" : "";
	string isNotCurrentUser = ((bool)ViewData["IsNotUsingCurrentUser"]) == true ? "checked" : "";
}
<div class="clearfix"></div>
<div class="row">
	<div class="col-md-12 col-xs-12 col-lg-12">
		<div class="x_panel">
			<div class="x_content">
				<div class="row">
					<form class="panel" id="activeDirectoryForm">
						<settings-element class="activeDirectory-settings col-md-12 col-xs-12 col-lg-12">
							<settings-header>
								<label class="activeDirectory-input">Использовать Active Directory: </label>
								<input name="activeDirectory-switch" type="checkbox" class="js-switch" data-toggle="#activeDirectory-main" onchange="settingsPage.changeAd('activeDirectory-switch')" @isUsing/>
							</settings-header>
							<settings-main id="activeDirectory-main" hidden>
								<settings-config>
									<label>Доступный домен Active Directory или локальной машины: </label>
									<div id="availableDomain">@ViewData["IsCurrentServerInDomain"]</div>
								</settings-config>
								<settings-element class="activeDirectory-settings col-md-12 col-xs-12 col-lg-12">
									<settings-header>
										<settings-config>
											<label>Не использовать параметры текущего пользователя: </label>
											<input name="activeDirectory-currentuser" type="checkbox" class="js-switch" data-toggle="#activeDirectory-adminsettings" onchange="settingsPage.changeAd('activeDirectory-currentuser')" @isNotCurrentUser />
										</settings-config>
									</settings-header>
									<settings-main id="activeDirectory-adminsettings" hidden>
										<div class="form-group">
											<label class="col-md-3 col-xs-4 col-lg-2" for="activeDirectory-login-admin">Логин администратора: </label>
											<input name="activeDirectory-login-admin" type="text" class="form-control col-md-9 col-xs-8 col-lg-10" id="activeDirectory-login-admin" placeholder="Логин" value="@ViewData["ActiveDirectoryDomainLogin"]">
										</div>
										<div class="form-group">
											<label class="col-md-3 col-xs-4 col-lg-2" for="activeDirectory-pass-admin">Пароль администратора: </label>
											<input name="activeDirectory-pass-admin" type="password" class="form-control col-md-9 col-xs-8 col-lg-10" id="activeDirectory-pass-admin" placeholder="Пароль">
										</div>
										<div>
											<input type="button" class="btn" value="Проверить" id="testAdmin" />
										</div>
									</settings-main>
								</settings-element>
							</settings-main>
						</settings-element>
						<input type="button" class="btn btn-success" value="Сохранить" id="saveAdSettings" />

					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section scripts{
	<script>
		$(() => {
			settingsPage.initAD();

			settingsPage.changeAd('activeDirectory-switch');
			settingsPage.changeAd('activeDirectory-currentuser');
		});

	</script>

}

MVCInfosV2Web/Views/Settings/Cerificates.cshtml
@{
	ViewBag.Title = "Сертификаты";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.TitlePage = "Настройка сервера";
	ViewBag.TitlePageSmall = ViewBag.Title;
	ViewBag.UseSearch = false;
}
<div>
	@using (Html.BeginForm(null, null, FormMethod.Post, htmlAttributes: new { @id = "__AjaxAntiForgeryForm" } @*"EditDepartment", "Administration", new { idFirm = Model.idFirm, idDepartment = Model.idDepartment, efd = EnumerableForDelete.Department }*@))
	{
		@Html.AntiForgeryToken()
	}
</div>
@{
	var newCert = (string)ViewData["cerificateNewEndDate"];
	var oldCert = (string)ViewData["cerificateOldEndDate"];

}
<div class="clearfix"></div>
<div class="row">
	<div class="col-md-12 col-xs-12 col-lg-12">
		<div class="x_panel">
			<div class="x_content">
				<div class="row">
					<form class="panel" id="activeDirectoryForm">
						@if (newCert == null)
						{
							<input type="button" class="btn btn-success" value="Создать самоподписанный сертификат" id="createCertificate" />
						}
						else
						{
							<div> Срок годности нового сертификата: @newCert</div>
							if (oldCert != null)
							{

								<div> Срок годности старого сертификата: @oldCert</div>
							}
							<input type="button" class="btn btn-success" value="Обновить сертификат" id="createCertificate" />
						}
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section scripts{

	<script type="text/javascript">
		$(() => {
			settingsPage.createCertificate();


		});
	</script>
}

MVCInfosV2Web/Views/Settings/FileHosting.cshtml
@{
	ViewBag.Title = "Хостинг файлов";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.TitlePage = "Настройка сервера";
	ViewBag.TitlePageSmall = "Хостинг файлов";
	ViewBag.UseSearch = true;
	
}



@section styles{
@Html.Raw(ViewData["plugins-style"])
	}
<div>
	@using (Html.BeginForm(null, null, FormMethod.Post, htmlAttributes: new { @id = "__AjaxAntiForgeryForm" } @*"EditDepartment", "Administration", new { idFirm = Model.idFirm, idDepartment = Model.idDepartment, efd = EnumerableForDelete.Department }*@))
	{
		@Html.AntiForgeryToken()
	}
</div>





<div class="x_panel">
	<div class="project-control">
		<div class="buttons-left">
			@*<span class="projects">
					<button type="button" class="btn btn-default button-selector" data-text="Не выбран проект">
						Не выбран проект
					</button>
					<span class="selector" id="selectorId">

					</span>
				</span>*@
			<button id="addHostButton" type="button" class="btn btn-success" data-text="Добавить хост">
				Добавить хост
			</button>
			@*<span>
					<label data-text="Задачи для:">
						Задачи для:
					</label>
				</span>*@
			@* @Html.ActionLink("Добавить задание в *", "AddNewTask", new { @idFirm = ViewData["idFirm"] }, new { @class = "btn btn-success" })*@
		</div>
		@*<div class="buttons-right">
				<div class="btn-group" data-toggle="buttons-radio">
					<button type="button" class="btn btn-default" link="True">Текущие</button>
					<button type="button" class="btn btn-default" link="False">Законченные</button>
					<button type="button" class="btn btn-default" link="null">Все</button>
				</div>
			</div>*@
	</div>
</div>
<div class="clearfix"></div>
<div class="row">
	<div class="col-md-12">
		<div class="x_panel">
			<div class="x_content">
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						Если нет никаких подключений, то данный сервер сам является файловым хостингом. Файлы хранятся в папке <code>LocaleTempFiles</code> в IIS.<br />
						Требуется настроить пересылку!

					</div>

					<div class="col-md-12 col-sm-12 col-xs-12">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>
										По умолчанию
									</th>
									<th>
										Наименование
									</th>
									<th>
										Короткая информация
									</th>
									<th>
										Управление
									</th>
								</tr>
							</thead>

							<tbody id="hostsBody"></tbody>

						</table>
						<button type="button" class="btn btn-primary" button-type="save">Сохранить</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@section modals{

	@using (Html.BeginForm(null, null, FormMethod.Post, htmlAttributes: new { @id = "__AjaxAntiForgeryForm" }))
	{
		@Html.AntiForgeryToken()
	}
	<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog">
		<div class="modal-dialog modal-lg" role="document">
			<div class="modal-content">
				@*<form id="new-host">*@
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title">
							Новый хост <small></small>
						</h4>
					</div>
					<div class="modal-body">
						<div class="form-horizontal form-label-left">
							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-theme">
									Тип подключения <span class="required">*</span>
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									@Html.Raw(ViewData["plugins"])
								</div>
							</div>
							<form>

							</form>
							@*<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-theme">
									Название <span class="required">*</span>
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									<input type="text" id="host-name" required class="form-control col-md-12 col-xs-12">
								</div>
							</div>

							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-end-date">
									Адрес загрузчика <span class="required">*</span>
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									<input type="text" id="host-uploaderurl" required class="form-control col-md-12 col-xs-12">
								</div>
							</div>

							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-description">
									Логин
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									<input type="text" id="host-login" class="form-control col-md-12 col-xs-12">
								</div>
							</div>


							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-priority">
									Пароль
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									<input type="password" id="host-password" class="form-control col-md-12 col-xs-12">
								</div>
							</div>

							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-priority">
									Повторить пароль
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									<input type="password" id="host-repeatpassword" class="form-control col-md-12 col-xs-12">
								</div>
							</div>

							<div class="form-group">
								<label class="control-label col-md-3 col-sm-3 col-xs-12" for="host-priority">
									Токен
								</label>
								<div class="col-md-9 col-sm-9 col-xs-12">
									<input type="password" id="host-token" class="form-control col-md-12 col-xs-12">
								</div>
							</div>*@
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
						<button type="button" class="btn btn-primary" button-type="submit">Добавить</button>
					</div>
				@*</form>*@
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
}



@section scripts{
	<script type="text/javascript">
		$(() => {
			settingsPage.setFormsCollection(@Html.Raw(Json.Encode(ViewData["plugins-forms"])));
			settingsPage.initFileHostings();
			settingsPage.pluginInit();
		});
	</script>
}

MVCInfosV2Web/Views/Settings/Organization.cshtml
@{
	ViewBag.Title = "Законодательные вопросы";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.TitlePage = "Настройка сервера";
	ViewBag.TitlePageSmall = "Законодательные вопросы";
	ViewBag.UseSearch = true;
}