MVCInfosV2Web/Controllers/ProjectManagerController.cs
using LingvoNET;
using Microsoft.AspNet.Identity;
using MvcInfos.ActiveDirectory;
using MvcInfos.ActiveDirectory.Extensions;
using MvcInfos.Attributes;
using MvcInfos.Entities.Firm;
using MvcInfos.Entities.UserConfigurations;
using MvcInfos.Models.ViewModels;
using MvcInfos.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace MvcInfos.Controllers
{
	[AuthorizeActiveDirectory(Roles = "project_manager,manager,administrator_server,administrator_firm", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager,PMServerSManager")]
    public class ProjectManagerController : Controller
    {
        private IApplicationRepository DBRepository { get; set; }
        public ProjectManagerController(IApplicationRepository repos)
        {
            DBRepository = repos;
        }

        // GET: ProjectManager
        public ActionResult Index()
        {
            return RedirectToAction("stats");
        }

        public ActionResult ProjectDetail(int idProject)
        {
            return View();
        }
        public async Task<ActionResult> PrintProjects(int? idFirm)
        {
            if (idFirm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var currentUserId = User.Identity.GetUserId();
            var employeeFirm = await DBRepository.EmployeeFirms.Where(firm => firm.Firm.FirmID == idFirm).Where(ff => ff.ApplicationUserId.Id.Equals(currentUserId)).Select(p => p).FirstOrDefaultAsync();
            if (employeeFirm != default(EmployeeFirm))
            {
                ViewData["firmName"] = employeeFirm.Firm.Name;
                ViewData["idFirm"] = idFirm;
            }

            return View();
        }
        public async Task<ActionResult> GetProjects(int? idFirm, bool? isCurrent)
        {
            if (idFirm == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.IsHasAccessRights(EnumerableRoles.project_manager))
            {
                var currentUserId = User.Identity.GetUserId();
                var employeeFirm = await DBRepository.EmployeeFirms.Where(firm => firm.Firm.FirmID == idFirm).Where(ff => ff.ApplicationUserId.Id.Equals(currentUserId)).Select(p => p).FirstOrDefaultAsync();
                if (employeeFirm != default(EmployeeFirm))
                {
                    ViewData["firmName"] = employeeFirm.Firm.Name;
                    ViewData["idFirm"] = idFirm;
                    if (isCurrent != null)
                    {
                        var myProjects = employeeFirm.ProjectEmployeeFirms.Where(prj => (prj.IsDeleted == false) && (prj.IsCurrent == isCurrent)).Select(o => o.Project.ProjectID);
                        return Json(myProjects.ToList(), JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var myProjects = employeeFirm.ProjectEmployeeFirms.Where(prj => (prj.IsDeleted == false)).Select(o => o.Project.ProjectID);
                        return Json(myProjects.ToList(), JsonRequestBehavior.AllowGet);

                    }
                }
            }
            if (User.IsHasAccessRights(EnumerableRoles.manager) || User.IsHasAccessRights(EnumerableRoles.administrator_firm))
            {
                var currentUserId = User.Identity.GetUserId();
                var employeeFirm = await DBRepository.EmployeeFirms.Where(firm => firm.Firm.FirmID == idFirm).Where(ff => ff.ApplicationUserId.Id.Equals(currentUserId)).Select(p => p).FirstOrDefaultAsync();
                if (employeeFirm != default(EmployeeFirm))
                {
                    ViewData["firmName"] = employeeFirm.Firm.Name;
                    ViewData["idFirm"] = idFirm;
                    if (isCurrent != null)
                    {
                        var myProjects = await DBRepository.Projects.Where(project => (project.PlannedFinishDate > DateTime.Now) == isCurrent).Select(o => o.ProjectID).ToListAsync();
                        return Json(myProjects, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var myProjects = await DBRepository.Projects.Select(o => o.ProjectID).ToListAsync();
                        return Json(myProjects, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            if (User.IsHasAccessRights(EnumerableRoles.administrator_server))
            {
                ViewData["firmName"] = (await DBRepository.Firms.FindAsync(idFirm)).Name;
                ViewData["idFirm"] = idFirm;
                if (isCurrent != null)
                {
                    var myProjects = await DBRepository.Projects.Where(project => (project.PlannedFinishDate > DateTime.Now) == isCurrent).Select(o => o.ProjectID).ToListAsync();
                    return Json(myProjects, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var myProjects = await DBRepository.Projects.Select(o => o.ProjectID).ToListAsync();
                    return Json(myProjects, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new List<int>(), JsonRequestBehavior.AllowGet);
        }

       private ActionResult GetProjectStatus(int? idProject)
        {
            ///TODO: Реализовать получение текущего статуса
            return null;
        }
        public async Task<ActionResult> _ProjectRowPartial(int? idFirm, int? idProject)
        {
            if ((idFirm == null) || (idProject == null))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (User.IsHasAccessRights(EnumerableRoles.project_manager))
            {
                var currentUserId = User.Identity.GetUserId();
                var employeeFirm = await DBRepository.EmployeeFirms.Where(firm => firm.Firm.FirmID == idFirm).Where(ff => ff.ApplicationUserId.Id.Equals(currentUserId)).Select(p => p).FirstOrDefaultAsync();
                if (employeeFirm != default(EmployeeFirm))
                {
                    var project = employeeFirm.ProjectEmployeeFirms.Where(proj => proj.Project.ProjectID == idProject.Value).Select(proj => new { @projectName = proj.Project.ProjectName, @createdDate = proj.Project.ProjectStartDate, @projectCode = proj.Project.ProjectCode }).FirstOrDefault();
                    if (project != null)
                    {
                        var userInfo = (await DBRepository.Projects.FindAsync(idProject)).ProjectEmployeeFirms.Where(projectEF => projectEF.StopWorking == null).Select(projectEF => new Tuple<string, string, string>(projectEF.EmployeeFirm.ApplicationUserId.Id, projectEF.EmployeeFirm.ApplicationUserId.Employee.Person.FamilyName, projectEF.EmployeeFirm.ApplicationUserId.Employee.Person.PhotoUrl)).ToList();
                        return PartialView("ProjectManagePartials\\_ProjectRowPartial", new ProjectRowPartialModel() { IdFirm = idFirm.Value, IdProject = idProject.Value, CreatedData = project.createdDate, ProjectName = project.projectName, ProcentComplete = 0, Stage = "Разрабатывается", UserInfo = userInfo, ProjectCod = project.projectCode });
                    }
                }
            }
            if (User.IsHasAccessRights(EnumerableRoles.manager) || User.IsHasAccessRights(EnumerableRoles.administrator_firm))
            {
                var currentUserId = User.Identity.GetUserId();
                var employeeFirm = await DBRepository.EmployeeFirms.Where(firm => firm.Firm.FirmID == idFirm).Where(ff => ff.ApplicationUserId.Id.Equals(currentUserId)).Select(p => p).FirstOrDefaultAsync();
                if (employeeFirm != default(EmployeeFirm))
                {
                    var project = (await DBRepository.Firms.FindAsync(idFirm)).Projects.Where(proj => proj.ProjectID == idProject).Select(proj => new { @projectName = proj.ProjectName, @createdDate = proj.ProjectStartDate, @projectCode = proj.ProjectCode }).FirstOrDefault();
                    if (project != null)
                    {
                        var userInfo = (await DBRepository.Projects.FindAsync(idProject)).ProjectEmployeeFirms.Where(projectEF => projectEF.StopWorking == null).Select(projectEF => new Tuple<string, string, string>(projectEF.EmployeeFirm.ApplicationUserId.Id, projectEF.EmployeeFirm.ApplicationUserId.Employee.Person.FamilyName, projectEF.EmployeeFirm.ApplicationUserId.Employee.Person.PhotoUrl)).ToList();
                        return PartialView("ProjectManagePartials\\_ProjectRowPartial", new ProjectRowPartialModel() { IdFirm = idFirm.Value, IdProject = idProject.Value, CreatedData = project.createdDate, ProjectName = project.projectName, ProcentComplete = 0, Stage = "Разрабатывается", UserInfo = userInfo, ProjectCod = project.projectCode });
                    }
                }
            }
            if (User.IsHasAccessRights(EnumerableRoles.administrator_server))
            {
                var project = (await DBRepository.Firms.FindAsync(idFirm)).Projects.Where(proj => proj.ProjectID == idProject).Select(proj => new { @projectName = proj.ProjectName, @createdDate = proj.ProjectStartDate, @projectCode = proj.ProjectCode }).FirstOrDefault();
                if (project != null)
                {

MVCInfosV2Web/Views/ProjectManager/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Administration/Admin/admins.cshtml";
}

<h2>Index</h2>

MVCInfosV2Web/Views/ProjectManager/PrintProjects.cshtml
@using MvcInfos.Entities.UserConfigurations;
@{
	ViewBag.Title = "Проекты";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.TitlePage = "Проекты";
	ViewBag.TitlePageSmall = ViewData["firmName"];
	ViewBag.UseSearch = true;
}


<div class="x_panel">
	<div class="project-control">
		<div class="buttons-left">
			@Html.ActionLink("Добавить проект", "CreateProject", "ProjectManager", new { @idFirm = ViewData["idFirm"] }, new { @class = "btn btn-success" })
		</div>
		<div class="buttons-right">
			<div class="btn-group" data-toggle="buttons-radio">
				<button type="button" class="btn btn-default" link="True">Текущие</button>
				<button type="button" class="btn btn-default" link="False">Законченные</button>
				<button type="button" class="btn btn-default" link="null">Все</button>
			</div>
		</div>

	</div>


</div>
<div class="clearfix"></div>
<div class="x_panel">
	@if (ViewData["idFirm"] == null)
	{
		<div class="alert alert-danger">
			<strong>Внимание!</strong> Проекты не могут быть показаны, вы не зарегистрировали организацию.
		</div>
	}
	else
	{
		<div id="mainProjectPage">


		</div>
	}
	<!-- end project list -->
</div><!-- /page content -->


@section scripts{

	<script type="text/javascript">
                $(document).ready(function () {
                    if ($(".progress .progress-bar")[0]) {
                        $('.progress .progress-bar').progressbar();
                    }
                    console.log(getParameterByName("isCurrent"));
                    var state = getParameterByName("isCurrent");
                    if (state == "True") {
                        updateRadioButtons($(".btn-group button[link='True']"));
                        loadProjects('mainProjectPage', @ViewData["idFirm"], true);
                    }
                    if (state == null) {
                        updateRadioButtons($(".btn-group button[link='null']"));
                        loadProjects('mainProjectPage', @ViewData["idFirm"], null);
                    }
                    if (state == "False") {
                        updateRadioButtons($(".btn-group button[link='False']"));
                        loadProjects('mainProjectPage', @ViewData["idFirm"], false);
                    }
                    clickOnButtonsRadio(@ViewData["idFirm"]);
                });
	</script>
}

MVCInfosV2Web/Views/ProjectManager/ViewDepartment.cshtml
@model MvcInfos.Models.ViewModels.CViewDogovor
@{
    ViewBag.Title = "ViewDepartment";
    Layout = "~/Views/ProjectManager/_LayoutProjectManager.cshtml";
}

<h2>ViewDepartment</h2>

<div>

    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.NameContract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameContract)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Firm)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firm)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        @if (Model.FIOs.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.FIOs)
            </dt>
            <dd>

            </dd>
            foreach (var item in Model.FIOs)
            {
                <dt>
                    
                </dt>
                <dd>
                   @Html.DisplayText(string.Format("{0}|{1}|{2}", item.FIO, item.EMail, item.PhoneNumber))
                </dd>
            }
        }
        else
        {
            <dt>
                @Html.DisplayNameFor(model => model.FIOs)
            </dt>
            <dd class="alert alert-danger">
                Нет контактных лиц
            </dd>


        }

    </dl>
</div>

MVCInfosV2Web/Views/ProjectManager/_LayoutProjectManager.cshtml
@using MvcInfos.Models.ViewModels;
@using MvcInfos.Entities.UserConfigurations
@using MvcInfos.ActiveDirectory.Extensions;
@model _LayoutProject
@{
    ViewBag.Title = "Управление проектами";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (User.IsHasAccessRights(EnumerableRoles.administrator_server) || (User.IsHasAccessRights(EnumerableRoles.administrator_firm)) || (User.IsHasAccessRights(EnumerableRoles.manager)))
{
    <h2>Управление проектами</h2>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="well nav">
                    
                    <div id="tree">
                    </div>
                   @* <ul class=" nav nav-pills nav-stacked" id="myTab">*@
                    <ul class="nav list-group"> 
                        @foreach (var item in Model.pmvm)
                        {
                            <li>
                                <a class="list-group-item" id="@string.Format("firm_{0}", item.Firm.IdFirm)" href="#"> @item.Firm.NameFirm<i class="glyphicon glyphicon-chevron-down"> </i></a>
                                <ul class="list-group-item">
                                    <li class="list-group-item">
                                        <a class="list-group-item  @(ViewContext.RouteData.Values["Action"].ToString() == "stats" ? "active" : "")" href="@Url.Action("stats", "ProjectManager", new {@idFirm = item.Firm.IdFirm })">
                                            Статистика
                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                        </a>
                                    </li>
                                    @*Проекты*@
                                    <li class="list-group-item">
                                        <a class="list-group-item" id="@string.Format("proj_{0}", item.Firm.IdFirm)" href="#"> Проекты<i class="glyphicon glyphicon-chevron-down"></i></a>
                                        <ul class="list-group-item">

                                            <li class="list-group-item ">
                                                <a class="list-group-item @(ViewContext.RouteData.Values["Action"].ToString() == "CreateProject" ? "active" : "")" href="@Url.Action("CreateProject", "ProjectManager", new {@idFirm = item.Firm.IdFirm })">
                                                    Создание проекта
                                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                                </a>
                                            </li>
                                            @foreach (var item1 in item.Projects)
                                            {
                                                <li class="list-group-item">
                                                    @if (((ViewContext.RequestContext.HttpContext).Request).Params["idProj"] != null)
                                                    {
                                                        <a class="list-group-item @((ViewContext.RouteData.Values["Action"].ToString() == "ViewProject")&(((ViewContext.RequestContext.HttpContext).Request).Params["idProj"].ToString() == Convert.ToString(item1.ProjectId)) ? "active" : "")" href="@Url.Action("ViewProject", "ProjectManager", new { @idProj = item1.ProjectId, @idFirm = item.Firm.IdFirm })">
                                                            @string.Format("{0}", item1.ProjectName)
                                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                                        </a>
                                                    }
                                                    else
                                                    {
                                                        <a class="list-group-item @((ViewContext.RouteData.Values["Action"].ToString() == "ViewProject") ? "active" : "")" href="@Url.Action("ViewProject", "ProjectManager", new { @idProj = item1.ProjectId, @idFirm = item.Firm.IdFirm })">
                                                            @string.Format("{0}", item1.ProjectName)
                                                            <span class="glyphicon glyphicon-chevron-right"></span>
                                                        </a>
                                                    }
             
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                </ul>
                                <script>
                                    $('#@string.Format("firm_{0}", item.Firm.IdFirm)').click(
                                        function () {
                                            console.log("firm_");
                                            $('#@string.Format("firm_{0}", item.Firm.IdFirm)').next().toggle();
                                        });
                                    $('#@string.Format("proj_{0}", item.Firm.IdFirm)').click(
                                        function () {
                                            console.log("proj_");
                                            $('#@string.Format("proj_{0}", item.Firm.IdFirm)').next().toggle();
                                        });
                                </script>
                            </li> 
                        }

                    </ul>
                </div>
            </div>
            <div class="col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="tab-content">
                            <div>
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{

}

MVCInfosV2Web/Views/ProjectManager/_ViewProject.cshtml
@model MvcInfos.Models.ViewModels.ViewProject
@{
    ViewBag.Title = "Проект " + Model.КОД;
    Layout = "~/Views/ProjectManager/_LayoutProjectManager.cshtml";
}
@using MvcInfos.Controllers

<h2>Проект: @Model.Название</h2>

<div>
    <div>
        <p>
            <button type="button" class="btn btn-danger" data-toggle="modal" title="Удалить" data-target="@string.Format("#myModalDel_{0}",@Model.id_project)">
                <span class="glyphicon glyphicon-trash" />
            </button>
            <a class="btn btn-danger" href="#" role="button">Удалить</a>
            @*<a class="btn btn-info" href="#" role="button">Редактировать</a>*@
            @Ajax.ActionLink("Редактировать", "_modal_project_edit", "ProjectManager",
           new { @idFirm = ViewData["idFirm"], @idProj = Model.id_project },
           new AjaxOptions
           {
               UpdateTargetId = string.Format("modalProjectEdit_{0}_in", "zxc123zxc"),
               InsertionMode = InsertionMode.Replace,
               HttpMethod = "GET",
               OnSuccess = string.Format("modalProjectEdit_{0}_ShowProducerEditModal", "zxc123zxc")
           },
               htmlAttributes: new { @class = "btn btn-info", @id = "chkOut" })
            @Ajax.ActionLink("Выбрать сотрудников с допуском", "_modal_project_add_user", "ProjectManager", new { @idFirm = ViewData["idFirm"], @idProj = Model.id_project },
               new AjaxOptions
               {
                   UpdateTargetId = string.Format("modalProjectAdd_{0}_in", "zxc123zxc"),
                   InsertionMode = InsertionMode.Replace,
                   HttpMethod = "GET",
                   OnSuccess = string.Format("modalProjectAdd_{0}_ShowProducerEditModal", "zxc123zxc")
               },
               htmlAttributes: new { @class = "btn btn-primary", @id = "chkOut" })
        </p>@*glyphicon glyphicon-edit*@
    </div>
    <div class="dropdown ">
        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Добавить
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li>
                @Ajax.ActionLink("Договор", "_modal_project_add_dogovor", "ProjectManager", new { @idFirm = ViewData["idFirm"], @idProj = Model.id_project },
    new AjaxOptions
    {
        UpdateTargetId = string.Format("modalProjectAddDogovor_{0}_in", "zxc123zxc"),
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET",
        OnSuccess = string.Format("modalProjectAddDogovor_{0}_ShowProducerEditModal", "zxc123zxc")
    },
    htmlAttributes: new { @id = "chkOut" })
            </li>




            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
    </div>


    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.КОД)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.КОД)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Otvetstven)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Otvetstven)
        </dd>

        @if (Model.dogovors.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.dogovors)
            </dt>
            <dd>

            </dd>
            foreach (var item in Model.dogovors)
            {
                <dt>

                </dt>
                <dd>
                    @Html.ActionLink(item,"ViewDepartment", new { @idFirm = ViewData["idFirm"], @idProj = Model.id_project, @dogovorName = item })
                </dd>
            }
        }
        else
        {
            <dt>
                @Html.DisplayNameFor(model => model.dogovors)
            </dt>
            <dd class="alert alert-danger">
                Нет выполняемых договоров в данный момент
            </dd>


        }
        @if (Model.employes.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.employes)
            </dt>
            foreach (var item in Model.employes)
            {
                <dd>
                    @Html.DisplayFor(model => item)
                </dd>
            }
        }
        else
        {
            <dt>
                @Html.DisplayNameFor(model => model.employes)
            </dt>
            <dd class="alert alert-danger">
                Нет сотрудников работающих на данном проекте
            </dd>
        }

    </dl>
</div>


<div>
    <!-- Modal -->
    <div class="modal fade" id="@String.Format("modalProjectAdd_{0}", "zxc123zxc")" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document" id="@string.Format("modalProjectAdd_{0}_in","zxc123zxc")">
        </div>
    </div>
</div>

<div>
    <!-- Modal -->
    @*Добавление договора*@
    <div class="modal fade" id="@String.Format("modalProjectAddDogovor_{0}", "zxc123zxc")" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document" id="@string.Format("modalProjectAddDogovor_{0}_in","zxc123zxc")">
        </div>
    </div>
</div>
<div>
    <!-- Modal -->
    @*Добавление договора*@
    <div class="modal fade" id="@String.Format("myModalDel_{0}",Model.id_project)" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document" id="@string.Format("myModalDel_{0}_in",Model.id_project)">
        </div>
    </div>
</div>

@Html.Action("_modal_project_delete", new { idProj = Model.id_project, efd = EnumerableForDelete.Project })
<div>
    <!-- Modal -->
    <div class="modal fade" id="@String.Format("modalProjectEdit_{0}", "zxc123zxc")" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document" id="@string.Format("modalProjectEdit_{0}_in","zxc123zxc")">
        </div>
    </div>
</div>
<script>

    @{
        var functionStart3 = "function " + string.Format("modalProjectAddDogovor_{0}_ShowProducerEditModal()", "zxc123zxc");
    }
    @functionStart3{
        console.log("load firm edit");
        $('#@string.Format("modalProjectAddDogovor_{0}", "zxc123zxc")').modal('show');
        $('#@string.Format("modalProjectAddDogovor_{0}", "zxc123zxc")').on('show.bs.modal', function () {
            $('#@string.Format("modalProjectAddDogovor_{0}_in", "zxc123zxc")').focus()
        });
    }


    @{
                var functionStart = "function " + string.Format("modalProjectAdd_{0}_ShowProducerEditModal()", "zxc123zxc");
            }
    @functionStart{
        console.log("load firm edit");
        $('#@string.Format("modalProjectAdd_{0}", "zxc123zxc")').modal('show');
        $('#@string.Format("modalProjectAdd_{0}", "zxc123zxc")').on('show.bs.modal', function () {
            $('#@string.Format("modalProjectAdd_{0}_in", "zxc123zxc")').focus()
        });
    }

    @{
                var functionStart1 = "function " + string.Format("modalProjectEdit_{0}_ShowProducerEditModal()", "zxc123zxc");
            }
    @functionStart1{
        console.log("load firm edit");
        $('#@string.Format("modalProjectEdit_{0}", "zxc123zxc")').modal('show');
        $('#@string.Format("modalProjectEdit_{0}", "zxc123zxc")').on('show.bs.modal', function () {
            $('#@string.Format("modalProjectEdit_{0}_in", "zxc123zxc")').focus()
        });
    }
</script>

MVCInfosV2Web/Views/ProjectManager/stats.cshtml
@using MvcInfos.Models.ViewModels;
@model StatsModel
@{
    ViewBag.Title = "Статистика";
    Layout = "~/Views/ProjectManager/_LayoutProjectManager.cshtml";
}

@foreach (var item in Model.pmvm)
{
    <h3>@item.Firm.NameFirm</h3>
    <ul class="list-group">
        <li class="list-group-item">
            <span class="badge">@item.ColVoPrj</span>
            Всего проектов:
        </li>
    </ul>
    <ul class="list-group">
        <li class="list-group-item">
            <span class="badge">@item.ColVoPrjDost</span>
            Всего доступно проектов:
        </li>
    </ul>
}
@*<h3>Всего проектов: <span class="label label-default">@Model.col_vo_prj</span></h3>*@