MVCInfosV2Web/Controllers/TaskManagerController.cs
using Microsoft.AspNet.Identity;
using MvcInfos.ActiveDirectory;
using MvcInfos.ActiveDirectory.Extensions;
using MvcInfos.Attributes;
using MvcInfos.Entities.Tasks;
using MvcInfos.Entities.UserConfigurations;
using MvcInfos.Extensions;
using MvcInfos.Models.ViewModels;
using MvcInfos.Plugin.Interfaces;
using MvcInfos.Repository;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MvcInfos.Controllers
{
	[AuthorizeActiveDirectory]
	public class TaskManagerController : Controller
	{
		private IApplicationRepository DBRepository { get; set; }
		private IPlugins Plugins { get; set; }
		public TaskManagerController(IApplicationRepository repos, IPlugins plugins)
		{
			Plugins = plugins;
			DBRepository = repos;
		}
		// GET: Index
		public ActionResult Index()
		{
			return View();
		}
		// GET: Calendar

		public ActionResult Calendar()
		{
			return View();
		}
		public ActionResult Tasks()
		{
			return View();
		}
		[AuthorizeActiveDirectory(Roles = "project_manager,manager,administrator_server,administrator_firm", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager,PMServerSManager")]
		public ActionResult TaskManager(int? idFirm, bool? isCurrent)
		{
			ViewData["idFirm"] = idFirm;
			ViewData["isCurrent"] = isCurrent;
			return View();
		}
		[AuthorizeActiveDirectory(Roles = "project_manager,manager,administrator_server,administrator_firm", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager,PMServerSManager")]
		public ActionResult NewTask()
		{
			return View();
		}

		public async Task<JsonResult> GetMyFirms()
		{
			var UserInfo = DBRepository.Users.Find(User.Identity.GetUserId());
			var EmployeeFirmInfo = await DBRepository.EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(UserInfo.Id)).Select(item =>
			new FirmModel()
			{
				IdFirm = item.Firm.FirmID,
				NameFirm = item.Firm.Name
			}).ToListAsync();

			foreach (var item in EmployeeFirmInfo)
			{
				foreach (var item1 in await GetUserFromFirm(item.IdFirm))
				{
					if (!item1.Fio.Equals(""))
					{
						item.Employees.Add(new TaskManagerModelEmployee()
						{
							Fio = item1.Fio,
							Id = item1.Id
						});
					}
				}
			}
			return this.JsonNetIso(EmployeeFirmInfo, JsonRequestBehavior.AllowGet);
		}

		[AuthorizeActiveDirectory(Roles = "project_manager,manager,administrator_server,administrator_firm", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager,PMServerSManager")]
		public async Task<ActionResult> GetProjects(int? idFirm)
		{
			var currentUserId = User.Identity.GetUserId();
			if (User.IsHasAccessRights(EnumerableRoles.project_manager))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var employeeFirm = firm.EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(currentUserId) && ef.IsDeleted == false).FirstOrDefault();
				if (employeeFirm == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				var projects = employeeFirm.ProjectEmployeeFirms.Where(pef => pef.StopWorking == null && pef.IsDeleted == false).Select(pef => new
				{
					@id = pef.Project.ProjectID,
					@code = pef.Project.ProjectCode,
					@name = pef.Project.ProjectName,
					@startDate = pef.Project.ProjectStartDate,
					@endDate = pef.Project.PlannedFinishDate
				});
				return Json(projects, JsonRequestBehavior.AllowGet);
			}
			if (User.IsHasAccessRights(EnumerableRoles.manager) || User.IsHasAccessRights(EnumerableRoles.administrator_firm))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var employeeFirm = firm.EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(currentUserId) && ef.IsDeleted == false).FirstOrDefault();
				if (employeeFirm == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				var projects = firm.Projects.Where(project => project.PlannedFinishDate > DateTime.Now && project.IsDeleted == false).Select(proj => new
				{
					@id = proj.ProjectID,
					@code = proj.ProjectCode,
					@name = proj.ProjectName,
					@startDate = proj.ProjectStartDate,
					@endDate = proj.PlannedFinishDate
				});
				//var projects = employeeFirm.ProjectEmployeeFirms.Where(pef => pef.StopWorking == null).Select(pef => new { @Id = pef.Project.ProjectID, @Name = pef.Project.ProjectName });
				return Json(projects, JsonRequestBehavior.AllowGet);
			}
			if (User.IsHasAccessRights(EnumerableRoles.administrator_server))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var projects = firm.Projects.Where(project => project.PlannedFinishDate > DateTime.Now && project.IsDeleted == false).Select(proj => new
				{
					@id = proj.ProjectID,
					@code = proj.ProjectCode,
					@name = proj.ProjectName,
					@startDate = proj.ProjectStartDate,
					@endDate = proj.PlannedFinishDate
				});
				//var projects = employeeFirm.ProjectEmployeeFirms.Where(pef => pef.StopWorking == null).Select(pef => new { @Id = pef.Project.ProjectID, @Name = pef.Project.ProjectName });
				return Json(projects, JsonRequestBehavior.AllowGet);

			}
			return Json(new { }, JsonRequestBehavior.AllowGet);
		}

		[AuthorizeActiveDirectory(Roles = "project_manager,manager,administrator_server,administrator_firm", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager,PMServerSManager")]
		public async Task<IEnumerable<TaskManagerModelEmployee>> GetUserFromFirm(int? idFirm)
		{
			var currentUserId = User.Identity.GetUserId();
			if (User.IsHasAccessRights(EnumerableRoles.project_manager))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var employeeFirm = firm.EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(currentUserId) && ef.IsDeleted == false).FirstOrDefault();
				if (employeeFirm == null)
				{
					return null;
				}
				var employees = firm.EmployeeFirms
					.Where(pef => pef.IsDeleted == false)
					.Select(pef => new TaskManagerModelEmployee()
					{
						Id = pef.ApplicationUserId.Id,
						Fio = (pef.ApplicationUserId.Employee.Person == null) ? "" : pef.ApplicationUserId.Employee.Person.Fio
					});
				return employees;
			}

			if (User.IsHasAccessRights(EnumerableRoles.administrator_server))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var employees = firm.EmployeeFirms
					.Where(pef => pef.IsDeleted == false)
					.Select(pef => new TaskManagerModelEmployee()
					{
						Id = pef.ApplicationUserId.Id,
						Fio = (pef.ApplicationUserId.Employee.Person == null) ? "" : pef.ApplicationUserId.Employee.Person.Fio
					});
				return employees;
			}
			return new List<TaskManagerModelEmployee>();
		}


		[AuthorizeActiveDirectory(Roles = "project_manager,manager,administrator_server,administrator_firm", Groups = "AdministratorServerSManager,AdministratorOrganizationSManager,PMServerSManager")]
		public async Task<ActionResult> GetUserFromProject(int? idFirm, int? idProject)
		{
			var currentUserId = User.Identity.GetUserId();
			if (User.IsHasAccessRights(EnumerableRoles.project_manager))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var employeeFirm = firm.EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(currentUserId) && ef.IsDeleted == false).FirstOrDefault();
				if (employeeFirm == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				var employees = DBRepository.ProjectEmployeeFirms
					.Where(pef => pef.StopWorking == null && pef.IsDeleted == false && pef.Project.ProjectID == idProject)
					.Select(pef => new
					{
						@Id = pef.EmployeeFirm.ApplicationUserId.Id,
						@Fio = pef.EmployeeFirm.ApplicationUserId.Employee.Person.Fio
					});
				return Json(employees, JsonRequestBehavior.AllowGet);
			}

			if (User.IsHasAccessRights(EnumerableRoles.manager) || User.IsHasAccessRights(EnumerableRoles.administrator_firm))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var employeeFirm = firm.EmployeeFirms.Where(ef => ef.ApplicationUserId.Id.Equals(currentUserId) && ef.IsDeleted == false).FirstOrDefault();
				if (employeeFirm == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}

				var project = firm.Projects.Where(proj => proj.ProjectID == idProject).FirstOrDefault();
				var employees = project.ProjectEmployeeFirms
				   .Where(pef => pef.StopWorking == null && pef.IsDeleted == false && pef.Project.ProjectID == idProject)
				   .Select(pef => new
				   {
					   @Id = pef.EmployeeFirm.ApplicationUserId.Id,
					   @Fio = pef.EmployeeFirm.ApplicationUserId.Employee.Person.Fio
				   });
				return Json(employees, JsonRequestBehavior.AllowGet);
			}
			if (User.IsHasAccessRights(EnumerableRoles.administrator_server))
			{
				var firm = (await DBRepository.Firms.FindAsync(idFirm));
				var project = firm.Projects.Where(proj => proj.ProjectID == idProject).FirstOrDefault();
				var employees = project.ProjectEmployeeFirms
				   .Where(pef => pef.StopWorking == null && pef.IsDeleted == false && pef.Project.ProjectID == idProject)
				   .Select(pef => new
				   {
					   @Id = pef.EmployeeFirm.ApplicationUserId.Id,
					   @Fio = pef.EmployeeFirm.ApplicationUserId.Employee.Person.Fio
				   });
				return Json(employees, JsonRequestBehavior.AllowGet);
			}
			return Json(new { }, JsonRequestBehavior.AllowGet);
		}


		[ValidateJsonAntiForgeryToken]
		[ActionName("AddNewTask")]
		public ActionResult AddNewTask(string parametrs)
		{
			if (parametrs == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var localThanReplace = HttpUtility.UrlDecode(System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(parametrs)));
			var convertedParametrs = HttpUtility.ParseQueryString(localThanReplace);
			var idFirm = Convert.ToInt32(convertedParametrs["idFirm"]);

MVCInfosV2Web/Views/Shared/_Layout.cshtml
@using MvcInfos.ActiveDirectory.Extensions;
@using MvcInfos.Entities.UserConfigurations;
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>@ViewBag.Title – СМенеджер</title>
	@Styles.Render("~/Content/css/summernote")
	@Styles.Render("~/Content/css/vendor")
	@Styles.Render("~/Content/css/main")
	@Styles.Render("~/Content/css/fonts")
	
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/jqueryui")
	@Scripts.Render("~/bundles/modernizr")
	@Scripts.Render("~/bundles/moment_with_locales_min")
	@Scripts.Render("~/bundles/bootstrap")
	@Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/vendors")
	@Scripts.Render("~/bundles/sitejs")
	@Scripts.Render("~/bundles/summernote")
	@Scripts.Render("~/bundles/uploadcare")

	@if (User.Identity.IsAuthenticated)
	{
		<script type='text/javascript'>
			window["NOT_INIT_SIDEBAR"] = true;
		</script>
	}
	@RenderSection("HeaderScripts", required: false)
	<script type='text/javascript'>
		//$(() => {
		//	$('#checkService').click();
		//});
		///FOR UPLOADCARE
		UPLOADCARE_LOCALE = 'ru';
		//UPLOADCARE_PUBLIC_KEY = '461a7657aacbde4094c3';
		$.validator.methods.date = function (value, element) {
			if (!value)
				return false;
			var splitVal = value.split(' ');
			var date = splitVal[0].split('-');
			var time = (splitVal.length == 2 ? splitVal[1] : '0:0:0').split(':');
			var _date = new Date(value);

			console.log(this.optional(element) || !/Invalid|NaN/.test(_date));
			return true;
		};

	</script>

	<script type='text/javascript'>
		var appInsights = window.appInsights || function (config) {
			function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } }
			var t = { config: config }, u = document, e = window, o = 'script', s = u.createElement(o), i, f; for (s.src = config.url || '//az416426.vo.msecnd.net/scripts/a/ai.0.js', u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ['Event', 'Exception', 'Metric', 'PageView', 'Trace', 'Ajax']; i.length;) r('track' + i.pop()); return r('setAuthenticatedUserContext'), r('clearAuthenticatedUserContext'), config.disableExceptionTracking || (i = 'onerror', r('_' + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o), s }), t
		}({
			instrumentationKey: '107f04e9-ce70-4835-8b04-d50697b18541'
		});

		window.appInsights = appInsights;
		appInsights.trackPageView();
	</script>


	@RenderSection("styles", required: false)
</head>
@if (User.Identity.IsAuthenticated)
{


	<body class="nav-md">
		@*<input type="button" hidden value="Launch Installer" id="checkService" onclick="window.open('file:///D:Projects/kurs_bd/WithProject/test.bat')" />*@
		<div class="container body">
			<div class="main_container">
				<div class="col-md-3 left_col">
					<div class="left_col scroll-view">
						<div class="navbar nav_title" style="border: 0;">
							<a href="@Url.Action("Index", "Home")" class="site_title"><i class="fa fa-group"></i> <span>СМенеджер</span></a>
						</div>
						<div class="clearfix"></div>
						<!-- menu profile quick info -->
						<div class="profile clearfix">
							@Html.Action("_LeftPhoto", "Home")
						</div>
						<!-- /menu profile quick info -->
						<br />
		

						@Html.Action("SidebarMenu", "Home")
						


						<!-- /menu footer buttons -->
						<div class="sidebar-footer hidden-small">
							<a data-toggle="tooltip" data-placement="top" title="Настройка">
								<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
							</a>
							<a data-toggle="tooltip" data-placement="top" title="На весь экран">
								<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
							</a>
							<a data-toggle="tooltip" data-placement="top" title="Lock">
								<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
							</a>
							<a data-toggle="tooltip" data-placement="top" title="Выход" href="login.html">
								<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
							</a>
						</div>
						<!-- /menu footer buttons -->
					</div>
				</div>
				<!-- top navigation -->
				<div class="top_nav">
					<div class="nav_menu">
						<nav>
							<div class="nav toggle">
								<a id="menu_toggle"><i class="fa fa-bars"></i></a>
							</div>

							@Html.Action("_LoginPartial", "Home")

						</nav>
					</div>
				</div>
				<!-- /top navigation -->
				<!-- page content -->
				<div class="right_col hamburger-panel" role="main">
					<div>
						@if (ViewData.ContainsKey("TitlePage"))
						{
							<div class="page-title">
								<div class="title_left">
									<h3>@ViewBag.TitlePage <small>@ViewBag.TitlePageSmall</small></h3>
								</div>
								@if (ViewData.ContainsKey("UseSearch"))
								{
									if (ViewBag.UseSearch == true)
									{
										<div class="title_right">
											<div class="col-md-5 col-sm-5 col-xs-10 form-group pull-right top_search">
												<div class="input-group">
													<input type="text" class="form-control" placeholder="Поиск...">
													<span class="input-group-btn">
														<button class="btn btn-default" type="button">Искать!</button>
													</span>
												</div>
											</div>
										</div>
									}
								}
							</div>
							<div class="clearfix"></div>

						}
						@RenderBody()
						<hr />

					</div>
				</div>

				<footer>
					<div class="pull-right">
						SManager - The project manager web app by Kupcov K.S. and <a href="https://colorlib.com">Gentelella</a> theme
						@*<p>&copy; @DateTime.Now.Year – Инфос V2. ПГУ версия</p>
							<p>&copy; @DateTime.Now.Year – Купцов К. С.</p>*@
						<div class="clearfix"></div>
					</div>
				</footer>
			</div>
		</div>
		<div>
			@RenderSection("modals", required: false)
		</div>
		@if (Request.IsAuthenticated)
		{
			if (User.IsHasAccessRights(EnumerableRoles.administrator_server) || User.IsHasAccessRights(EnumerableRoles.administrator_firm) || User.IsHasAccessRights(EnumerableRoles.manager))
			{
				<script type="text/javascript">
                $(document).ready(function () {
					layoutLoader.layoutInit();
					@*layoutLoader.loadFirms([{ targetElementId: '#projectList' }, {
						targetElementId: '#taskList',
						innerHtml: '<li><a><i class="fa fa-tasks"></i> Задачи<span class="fa fa-chevron-down"></span></a>'+
											'<ul class="nav child_menu">'+
												'<li><a href="@Url.Action("Tasks", "TaskManager")">Мои задачи</a></li>'+
												'<li><a href="@Url.Action("TaskManager", "TaskManager")">Менеджер</a></li>'+
						'<li><a href="@Url.Action("NewTask", "TaskManager")">Назначить задачу</a></li>' +
						'</ul></li>'
						}]);*@

		});

				</script>
			}
		}
		@RenderSection("scripts", required: false)
	</body>
															}
															else
															{
																<body class="login">
																	@RenderBody()
																	@RenderSection("scripts", required: false)
																</body>		}

</html>